### ISSUE TITLE
minSdk error  

### ISSUE THREAD

**Issue by Bhaskar224** [covidgreen/react-native-exposure-notification-service#108]
## Error after installation 
After i install this package through npm i got minSdk error before installing this package the project was working properly

## Error:

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 949 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Task :app:processDebugMainManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
18 actionable tasks: 2 executed, 16 up-to-date
D:\toSend\test\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\toSend\test\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at makeError (D:\toSend\test\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\toSend\test\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\toSend\test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\toSend\test\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
```

## npx react-native info:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.38 GB / 15.86 GB
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.12.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 29.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7322048
    Visual Studio: 16.9.31205.134 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.8
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Can you please respond asap, am i doing anything wrong?

**Comment by Bhaskar2480** [comment]
> ## Error after installation
> After i install this package through npm i got minSdk error before installing this package the project was working properly
> 
> ## Error:
> ```
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 949 file(s) to forward-jetify. Using 8 workers...
> info Starting JS server...
> info Installing the app...
> 
> > Task :app:processDebugMainManifest FAILED
> 
> See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
> 
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
> 18 actionable tasks: 2 executed, 16 up-to-date
> D:\toSend\test\android\app\src\debug\AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
>         Suggestion: use a compatible library with a minSdk of at most 21,
>                 or increase this project's minSdk version to at least 23,
>                 or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugMainManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
>         Suggestion: use a compatible library with a minSdk of at most 21,
>                 or increase this project's minSdk version to at least 23,
>                 or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> D:\toSend\test\android\app\src\debug\AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
>         Suggestion: use a compatible library with a minSdk of at most 21,
>                 or increase this project's minSdk version to at least 23,
>                 or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugMainManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0-rc02] C:\Users\bhask\.gradle\caches\transforms-2\files-2.1\bdf7cf6efd79ab0a8a8d08d27829808a\jetified-security-crypto-1.0.0-rc02\AndroidManifest.xml as the library might be using APIs not available in 21
>         Suggestion: use a compatible library with a minSdk of at most 21,
>                 or increase this project's minSdk version to at least 23,
>                 or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s
> 
>     at makeError (D:\toSend\test\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
>     at D:\toSend\test\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async runOnAllDevices (D:\toSend\test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
>     at async Command.handleAction (D:\toSend\test\node_modules\@react-native-community\cli\build\index.js:186:9)
> info Run CLI with --verbose flag for more details.
> ```
> 
> ## npx react-native info:
> ```
> info Fetching system and libraries information...
> System:
>     OS: Windows 10 10.0.19042
>     CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
>     Memory: 7.38 GB / 15.86 GB
>   Binaries:
>     Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: Not Found
>     npm: 7.12.0 - C:\Program Files\nodejs\npm.CMD
>     Watchman: Not Found
>   SDKs:
>     Android SDK:
>       API Levels: 28, 29
>       Build Tools: 29.0.2, 30.0.3, 31.0.0
>       System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
>       Android NDK: Not Found
>     Windows SDK: Not Found
>   IDEs:
>     Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7322048
>     Visual Studio: 16.9.31205.134 (Visual Studio Community 2019)
>   Languages:
>     Java: 11.0.8
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.1 => 17.0.1 
>     react-native: 0.64.1 => 0.64.1 
>     react-native-windows: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> Can you please respond asap, am i doing anything wrong?

Same problem

**Comment by Bhaskar2480** [comment]
??

**Comment by colmharte** [comment]
minSDK version for the module is 23
